= AWS support plans

AWS has lots of premium support plans that you can opt in to.

By default, the only support you get is billing support. For everything else, you need to pay for a support plan.

There are four main support plans:

* *Developer*: Recommended if you are experimenting or testing in AWS.
* *Business*: Minimum recommended tier if you have production workloads in AWS.
* *Enterprise On-Ramp*: Recommended if you have production and/or business critical workloads on AWS.
* *Enterprise*: Recommended if you have business and/or mission critical workloads on AWS.

Each plan has a different SLA, which determines how quickly support will respond to your requests. With the Enterprise On-Ramp and Enterprise plans, you get access to a pool of Technical Account Managers (TAM), who provide proactive guidance and will basically help you with anything AWS related, and get you access to other experts within AWS if necessary. With Enterprise you actually get a designated TAM — a single point of contact.
