= Logging and auditing

== CloudWatch Logs

* Gather application and system logs.
* Define expiration policies.
* Encrypt logs with KMS.

EC2 instances, or even on-premises servers, send logs to CloudWatch. This requires the *Unified CloudWatch Agent* to be installed on the client server. The client application sends application logs and/or system logs to CloudWatch.

Logs can also be sent from AWS Lambda functions, which just require the necessary permissions to add CloudWatch Logs.

The *Amazon Elasticsearch Service* can be integrated with CloudWatch to enable real-time processing, using something called a *subscription filter*. AWS Lambda can also be used for real-time processing.

== AWS CloudTrail

This is an *auditing service* — ie. it is all about understanding who did what and when.

CloudTrail logs *API activity* for auditing purposes. Whenever an API call is made in an account, CloudTrail records the details — the user, the resource, the time, etc. This includes calls made via the AWS Management Console, the AWS CLI, SDKs, and other clients.

By default, management events are logged and retained for 90 days. But if we create a CloudTrail _Trail_, we can capture those events in S3 and retain them indefinitely. A Trail can be within a region, or all regions.

*CloudWatch Events* can be triggered based on API calls made to CloudTrail. So, when we record in CloudTrail a certain event, we can have CloudWatch Events trigger something based on that.

CloudTrail events cna also be streamed to CloudWatch Logs.

== VPC Flow Logs

This is about logging what happens in an account at the network level. Flow logs capture information about the IP traffic going to and from network interfaces in a VPC.

Flow logs can be created at the following levels:

* VPC
* Subnet
* Network interface (which is attached to EC2 instances)

Flow log data is stored in CloudWatch Logs.

== Access Logs

*Elastic Load Balancing Access Logs* capture detailed information about requests sent to a load balancer. These can be used to analyze traffic patterns and troubleshoot issues. You can use these logs to identify the requester, IP, request type, etc. Optionally, this information can be stored in S3.

*S3 Access Logs* provide detailed records for any requests that are made to a target bucket. The logs will include information such as the requester, bucket name, request time, request action, response status, and any error codes.
