= Penetration testing

Penetration testing is the practice of testing your application's security by simulating an attack, with the aim of identifying vulnerabilities that could be exploited in a real attack. Pen testing is typically undertaken by security experts.

AWS has a customer support policy for penetration testing which, in summary, says that customers are allowed to carry out pen tests on their own AWS resources, without prior approval, for a specific set of permitted services, which include:

* EC2, WAF, NAT gateways, and ELB
* RDS
* CloudFront
* Aurora
* API Gateways
* AppSync
* Lambda and Lambda Edge functions
* Lightsail resources
* Elastic Beanstalk environments
* Elastic Container Service
* Fargate
* Elasticsearch
* FSx
* Transit Gateway
* S3-hosted applications (but targeting S3 buckets directly is strictly prohibited)

Prohibited activities include:

* DNS zone walking via Route 53 Hosted Zones.
* DNS hijacking via Route 53
* DNS pharming via Route 53
* Port flooding
* Protocol flooding
* Request flooding (login request flooding, API request flooding)

In addition, Denial of Service (DoS), Distributed Denial of Service (DDoS), Simulated DoS, and Simulated DDoS are subject to the DDoS Simulation Testing policy, and are essentially all prohibited by default.

For more information: +
https://aws.amazon.com/security/penetration-testing/
