= Security management

The following services help you to manage security in your AWS environments.

== AWS Security Hub

* Provides a comprehensive view of security alerts and security posture across your AWS accounts.
* Aggregates, organizes, and prioritizes security alerts (or findings) from multiple AWS services.
* Continuously monitors your environment using automated security checks.
* You can configure security standards to validate your environments against, including:
  ** AWS Foundational Security Best Practices v1.0.0
  ** CIS AWS Foundations Benchmark v1.2.0
  ** PCI DSS v3.2.1

== AWS Security Bulletins

* Security and privacy events affecting AWS services.
* Published on a web page, and also available via RSS feed.

== AWS Trust & Safety Team

* You should contact the AWS Trust & Safety Team if you find AWS resources that are being used for:
  ** Spam
  ** Port scanning
  ** Denial of Service (DoS) attacks
  ** Intrusion attempts
  ** Hosting of objectionable or copyrighted content
* Their email address is abuse@amazonaws.com.
