= Functions in Bash

As in almost any programming language, in Bash you can use functions to group pieces of code in a logical way, and to implement recursion.

You declare a function with the following syntax:

----
function [function_name] {
  # function body
}
----

This is an _explicit_ function declaration. _Implicit_ function declarations are possible with the following syntax:

----
[function_name] {
  # function body
}
----

.Examples
[source,bash]
----
# Explicit declaration.
function some_function () {
  return 0
}

# Implicit declaration.
some_function () {
  return 0
}
----

The explicit alternative gives more readability, but the implicit one is the POSIX standard so it is more portable.

The function body is placed inside the curly braces.

Functions don't need to be declared in any specific order.

== Parameters

In Bash, doing any of the following operations involves the exact same syntax:

* Calling a function.
* Running a program.
* Running a built-in command.

It means that a variable number of arguments can be passed to any function (or program or built-in command). It is up to the function or program to verify that any required arguments have been provided.

In Bash functions, like Bash scripts, functions are indexed – not named. `$1` is the first argument, `$2` is the second argument, and so on.

In the following example, the function `e` prints the first argument it receives.

[source,bash]
----
function e {
  echo $1
}
----
