= Iteration (loops)

Loops are a *control structure* that allow you to execute a block of code multiple times. In Bash, there are several types of loops. Each has different use cases.

== For loops

A `for` loop is used to iterate over a list of items.

[source,bash]
----
for item in list; do
  # Commands to execute for each item.
done
----

C-style `for` syntax is also supported:

[source,bash]
----
for ((i=0; i<10; i++)); do
  # Commands here will be executed exactly 10 times.
done
----

`for` loops are great for looping through dynamically-generated lists of things, like files found on the local filesystem, or for repeating a task a fixed number of times.

== While loops

A `while` loop continues to execute as long as a specified condition is true.

[source,bash]
----
while [ condition ]; do
  # Commands to execute while condition is true.
done
----

`while` loops are useful when you need to wait for a process to finish, to monitor system state, or to continue to read input until a precondition changes.

== Until loops

The `until` loop is similar to the `while` loop, except it is inverted: the loop executes for as long as the condition is `false`.

[source,bash]
----
until [ condition ]; do
  # Commands to execute until condition is true.
done
----

`until` is useful for doing things like running commands until a file exists, or until a service starts, or otherwise polling something until success.

== Nested loops

You can nest loops within each other to perform more complex iterations.

[source,bash]
----
#!/bin/bash

log_dir="/Users/nana/logs"
error_patterns=("ERROR" "FATAL" "CRITICAL")

log_files=$(find "$log_dir" -name "*.log" -mtime -1)

for log_file in $log_files; do
  for pattern in "${error_patterns[@]}"; do
    echo -e "\nNumber of ${error_patterns[0]} logs found in $log_file:"
    grep -c "${error_patterns[0]}" "$log_file"
  done
done
----
