= Git worktrees

// TODO: Add main documentation on Git worktrees.

Create a worktree from an existing branch:

[source,sh]
----
git worktree add ../<worktree-directory-name> <existing-branch-name>
----

To create a new branch in a new worktree in a single step:

[source,sh]
----
git worktree add -b <new-branch-name> ../<worktree-directory-name>
----

Branches off `HEAD` by default.

Other useful commands:

[source,sh]
----
git worktree list                      # Show all worktrees.
git worktree remove ../myrepo-feature  # Remove a worktree.
git worktree prune                     # Clean up stale entries.
----

== Bare repository

A bare repository has no working directory, so there's nothing to "check out"
in the usual sense. You can't switch branches in a bare repository as you
would a normal repository.

However, you can set the bare repository's default branch as you would any
other repository. This is the branch that gets checked out when someone clones
a bare repository. It's what is shown in the terminal prompt, where supported.

[source,sh]
----
git symbolic-ref HEAD refs/heads/<default-branch-name>
----

Verify the default branch name:

[source,sh]
----
git symbolic-ref HEAD
----

[TIP]
======
If you change the default branch in the upstream repository (eg. via the
GitHub UI), it is RECOMMENDED to update the symbolic ref for `HEAD`,
effectively changing the default branch name, in all cloned repositories
downstream, too.
======
