= Pricing for other AWS services

== S3 pricing

You pay for:

* *Storage class*, eg. Standard or IA.
* *Storage quantity*: the data volume store in your buckets on a per-GB basis.
* *Number of requests*, eg. GET, PUT, POST, LIST, COPY.
* *Life cycle transition requests*, ie. moving data between storage classes.
* *Data transfer* our of an S3 region is charged.
* *Retrievals and Requests* for some storage classes like Glacier.

== EBS pricing

You pay for:

* *Volumes*: Volume storage for all EBS volume types is charged by the amount of GB _provisioned_ (not used) per month.
* *Snapshots*: Based on the amount of space consumed by snapshots, which are stored in S3. Copying snapshots is charged on the amount of data copied across regions.
* *Data transfer*: Inbound data is free, outbound data charges are tiered.

== RDS pricing

You pay for:

* *Clock hours of server uptime*, ie. the amount of time the DB instance is running.
* *Database characteristics*, eg. database engine, size and memory class.
* *Database purchase type*, eg. on-demand, reserved.
* The *number of database instances*.
* *Provisioned storage*. Backup is included up to 100% of the size of the DB.
* *Additional storage*: The amount of storage in addition to the provisioned storage is charged per GB per month.
* *Requests*: The number of input and output requests to the DB.
* *Deployment type*: Single AZ or Multi-AZ.
* *Reserved Instances*: RDS RIs can be purchased with no up-front, partial up-front, or all up-front terms.

== DynamoDB pricing

You pay for:

* Reading, writing, and storing data.
* For *on-demand capacity mode*, you are charged only for reads and writes, and there's no need to specify how much capacity is required. This is a good option for unpredictable workloads.
* For *provisioned capacity mode*, where you specify the number of reads and write per second. It can use auto-scaling. This is good for predictable workloads, and consistent traffic or gradual changes.

== CloudFront pricing

You pay for:

* *Traffic distribution*: Data transfer and request pricing varies across regions, and is based on the edge location from which the content is served.
* *Requests*: You pay for the number and type of requests (HTTP and HTTPS have different pricing) and the geographic region in which they are made.
* *Data transfer out*: Quantity of data transferred out from CloudFront edge locations.

There are additional chargeable items, too, such as invalidation requests, field-level encryption requests, and custom SSL certificates.

== Lambda pricing

You pay for:

* *Number of requests*
* *Duration of a request* (rounded up to the nearest millisecond)
* The price is also dependent on the amount of *memory* that is allocated to the function.
