= Benefits

* *Multi-cloud*: Terraform is cloud-agnostic and can be used to manage resources in multiple cloud providers. By declaring your infrastructure as code in Terraform files, you can easily reproduce your infrastructure on another cloud provider, or even on-premises, reducing vendor lock-in.

* *Stateful*: It allows you to track your resource changes throughout your deployment in a state file, which is the single source of truth for what your environments look like at any one moment in time. Terraform itself uses this state file to determine what changes need to be made to your infrastructure, so that the state file eventually matches your desired configuration.

* *Version controlled*: Terraform files are plain text files that can be version controlled. This allows you to track changes to your infrastructure over time, and to collaborate with others on your infrastructure configuration. The infrastructure configuration may be maintained alongside the application code, eg. in the same repository.

* *Declarative*: You declare what you want the end state of your infrastructure to be, and Terraform builds it. You don't need to write out a bunch of imperative commands to create, update, or delete resources. Terraform figures that out.

* *No manual click-ops*: You don't need to manually manage infrastructure via your cloud provider's web console or CLI. As well as being time-consuming, this manual approach to infrastructure management also has other overheads, such as the management of access permissions and the tracking of changes.

* *Reduced risk of human error*: As well as reducing the costs associated with operating infrastructure manually, you can also reduced risks associated with human error. With Terraform, we can declare what we want, test it, and _then_ apply it.

* *High levels of automation* are possible when infrastructure is defined as code. For example, infrastructure can be automatically provisioned and destroyed as part of a CI/CD pipeline.

* *Cost savings* can be achieved, for example by tearing down non-production infrastructure at the end of each working day, so you're not paying for those resources outside of office hours.

* *Disaster recovery*: You can more quickly restore your infrastructure in the event of a disaster such as a data center outage. Because of the increased speed with which infrastructure can be recreated from scratch, you may choose to save further money by not maintaining a "hot standby" environment.
