= Terraform - AWS: Elastic IPs

The following is a simple configuration for an EC2 instance.

.main.tf
[source]
----
resource "aws_instance" "web_server" {
  ami           = "ami-0c55b159cbfafe1f0" # Amazon Linux 2
  instance_type = "t3.micro"

  vpc_security_group_ids = [aws_security_group.web_sg.id]

  user_data                   = file("user_data.sh")
  user_data_replace_on_change = true
}
----

By default, instances will be assigned a public IP address.

Unfortunately, there are some limitations with this configuration:

* Whenever we make changes to the configuration and `apply` those changes, the instance will be replaced. There will be downtime while the old instance is being stopped and the new instance is being started. (This is Terraform's default behavior: when a resource needs to be updated, it first terminates the existing resource before creating a replacement one.)

* The public IP address will change every time the instance is replaced. This means that if we have a DNS record pointing to the public IP address, we will need to update the DNS record every time the instance is replaced.

We can fix the second issue by assigning an Elastic IP address to the instance. An Elastic IP address is a static public IP address that can persist across instance replacements.

[source]
----
/* Define an Elastic IP address with the name "web_server": */
resource "aws_eip" "web" {
  /* This needs to be added in new versions of AWS Provider */
  domain   = "vpc"

  /* Assign the Elastic IP address to the current "web_server" instance. */
  instance = aws_instance.web_server.id
}

resource "aws_instance" "web" {
  // ...
}
----

To solve the first issue, we can use the `lifecycle` block and an argument that specifies that replacement resources must be created before the old resources are destroyed – ensuring minimal downtime when instances are replaced. (A few users may loose connection in the few seconds it takes to reassign the Elastic IP address to the new instance. Also the new instance may not have yet finished its startup scripts, ready to receive traffic.)

[source]
----
resource "aws_instance" "web" {
  // ...

  lifecycle {
    create_before_destroy = true
  }
}
----
