= Java: Classes

Java is an object-oriented programming language, and classes are the fundamental building blocks of Java programs. A class is a blueprint for creating *objects*, which are said to be *instances* of their class.

.A simple class
[source,java]
----
class Calculator {
  public int add(int n1, int n2) {
    return n1 + n2;
  }

  // Other methods...
}

/* Usage example: */
public class ClassesInJava {
  public static void main(String[] args) {

    Calculator calc = new Calculator();

    int result = calc.add(1, 2);
    System.out.println(result); // 3

  }
}
----

In the above example, the `Calculator` class is just a container for a group of standalone functions that do not share any state. More commonly, methods operate on instance variables, which are properties of the class that hold data relevant to a particular instance.

[source,java]
----
class MyClass {
  int prop;
}
----

Instance variables are accessed via instance objects.

[source,java]
----
public class ClassesInJava {
  public static void main(String[] args) {

    MyClass cls = new MyClass();
    cls.prop = 5;

    System.out.println(cls.prop); // 5

  }
}
----

You can also have static variables, too, which are shared across all instances.

[source,java]
----
class MyClass {
  static int staticProp;
}
----

Static variables are accessed via the class name, rather than an instance object.

[source,java]
----
public class ClassesInJava {
  public static void main(String[] args) {

    MyClass.staticProp = 5;
    System.out.println(MyClass.staticProp); // 5

  }
}
----

A *static block* can be used to initialize variables. A static block is called once only, when the class is loaded into memory - but not when you subsequently create instances of the class. Static blocks are useful for initializing static variables, which are shared across all instances of the class. But in most use cases it is sufficient to assign a static variable's value with the variable declaration.

[source,java]
----
class MyClass {
  static int staticProp;

  static {
    staticProp = 1;
  }
}
----

If you want to "load a class" without actually creating an instance of it, you need to use `Class.forName("ClassName")`. You will typically call this from another class. This is necessary if you want to initialize static variables in a class (by executing its static blocks) but you don't want to create an instance of the class. This feature is used rarely.

Constructors must be used to initialize instance variables.

[source,java]
----
class MyClass {
  int prop;

  public MyClass() {
    prop = 1;
  }
}
----

You can also initialize static variables from constructors, but it's not a common pattern because it doesn't really make sense logically. Best practice is to set static variables directly or via static blocks.

[source,java]
----
class MyClass {
  static int staticProp;

  public MyClass() {
    staticProp = 1;
  }
}
----

In Java, you can have multiple methods of the same name, as long as they have different parameters. Return types may vary. This is called *method overloading*.

[source,java]
----
class Calculator {
  public int add(int n1, int n2) {
    return n1 + n2;
  }

  public int add(int n1, int n2, int n3) {
    return n1 + n2 + n3;
  }
}
----

Methods can be static, too. You cannot access instance variables from static methods. If you wanted to do this, you'd need to pass in an instance of the class, and access the instance variables via that instance.

[source,java]
----
class Calculator {
  public static int multiply(int n1, int n2) {
    return n1 * n2;
  }
}
----

Static methods are accessed via the class name, rather than an instance object, using the same notation as for static variables.

[source,java]
----
public class ClassesInJava {
  public static void main(String[] args) {

    result = Calculator.multiply(2, 3);
    System.out.println(result); // 6

  }
}
----
