= Java: Inner classes

In Java, it is possible to define a class within another class. These are called *inner classes*.

[source,java]
----
class A {
  int age;

  public void show() {
    System.out.println("Hello");
  }

  class B {
    public void display() {
      System.out.println("World");
    }
  }
}
----

Usage:

[source,java]
----
A a = new A();
a.show(); // "Hello"

/* B belongs to A. The type is A.B, and instances are created
via an instance of A. */
A.B b = a.new B();
b.display(); // "World"
----

Inner classes can be static, too. Only inner classes can be static; it is not possible to create an outer static class.

[source,java]
----
class A {
  static class C {
    public void print() {
      System.out.println("Print");
    }
  }
}
----

Static inner classes are not bound to an instance of the outer class, so the access syntax is different.

[source,java]
----
A.C c = new A.C();
c.print(); // "Print"
----

You can have anonymous inner classes, too. This is useful when you know a subclass will be used once only, and you don't want to define a separate class for it. The syntax is unusual. You define the design of the subclass (technically, an inner class) _after_ its instantiation!

[source,java]
----
A a2 = new A() {
  public void show() {
    System.out.println("Hello from the anonymous class");
  }
};

a2.show(); // "Hello from the anonymous class"
----

You can use anonymous inner classes to implement abstract classes and then immediately instantiate them. This is a common pattern.
