= Java: Interfaces

There are three types of interface in Java:

* *Normal interfaces*: any interface with two or more methods.

* *Functional interfaces*: (aka. Single Abstract Method, SAM) an interface with only one abstract method. Built-in examples include `Runnable`, `Callable`, `Comparator`, `ActionListener` etc. We can create our own functional interfaces as well.

* *Marker interfaces*: an interface with no methods, aka. a blank interface. Examples include `Serializable`, `Cloneable`, `Remote`, `RandomAccess` etc. These interfaces are used to provide some special information to JVM or compiler. For example, a class that implements the `Serializable` interface can be serialized and deserialized, which means its state (data) can be saved and restored from disk.

All methods in an interface are `public` and `abstract` by default.

[source,java]
----
interface Computer {
  void code();
}

class Desktop implements Computer {
  public void code() {
    System.out.println("Coding on Desktop");
  }
}
----

From Java 8 (released 2014) onwards, we can have default and static methods defined directly in interfaces themselves.

You can also define variables in an interface. They MUST be initialized when declared – because, in interfaces, variables are `public static final` by default. This means they are constants. Including these in an interface just means there's a single place to define them for all classes that implement the interface. Everything else defined in an interface MUST be explicitly implemented in the implementing classes.

[source,java]
----
interface Computer {
  void code();
  int max = 100;
}
----

Interfaces can extend other interfaces.

[source,java]
----
interface X {
  void run();
}

interface Y extends X {
  void jump();
}
----

Classes can implement multiple interfaces, which is not possible with inheritance from abstract classes. This allows for more flexible designs and the ability to mix behaviors from different sources.

[source,java]
----
class Laptop implements Computer, Y {
  public void code() {
    System.out.println("Coding on Laptop");
  }

  /* Required from the X interface. */
  public void run() {}

  /* Required from the Y interface. */
  public void jump() {}
}
----
