= Java: toString() and hashCode()

The `toString()` method is used to get a string representation of an object. The default implementation of the `toString()` method returns the class name and the hash code of the object.

[source,java]
----
Object obj = new Object();
System.out.println(obj); // "java.lang.Object@15db9742"

/* Same as... */
System.out.println(obj.toString()); // "java.lang.Object@15db9742"
----

The `hashCode()` method is used to get the hash code of an object. The default implementation of the `hashCode()` method returns a unique integer value (hexadecimal format) for each object. The hash is based on the values of the object.

[source,java]
----
System.out.println(obj.hashCode()); // "366712642"
----

Both the `toString()` and `hashCode()` methods can be overridden in a class to provide a more meaningful string representation and hash code.

[source,java]
----
class Laptop {
  String model;
  int price;

  @Override
  public String toString() {
    return "Model: " + model + ", Price: " + price;
  }

  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((model == null) ? 0 : model.hashCode());
    result = prime * result + price;

    return result;
  }
}

Laptop laptop1 = new Laptop();
laptop1.model = "Dell XPS 15";
laptop1.price = 2000;

System.out.println(laptop1);            // "Model: Dell XPS 15, Price: 2000"
System.out.println(laptop1.toString()); // "Model: Dell XPS 15, Price: 2000"
----

However, there is a problem with the above implementation. If we add the following code, we expect `laptop1.equals(laptop2)` to return `true`, because both laptops are exactly the same model and have the same price.

[source,java]
----
Laptop laptop2 = new Laptop();
laptop2.model = "Dell XPS 15";
laptop2.price = 2000;

boolean result = laptop1.equals(laptop2);
System.out.println(result); // false
----

To fix this, we also need to override the `equals()` method. Internally, the `equals()` method uses the `hashCode()` method to compare if two objects encapsulate the same data (since the hashcode is based on the values of the object). Therefore, if we implement a custom `hashCode()` method, we should also override the default logic for `equals()` to maintain the contract between the two methods.

Here's the full implementation:

[source,java]
----
class Laptop {
  String model;
  int price;

  @Override
  public String toString() {
    return "Model: " + model + ", Price: " + price;
  }

  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((model == null) ? 0 : model.hashCode());
    result = prime * result + price;
    return result;
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj)
      return true;
    if (obj == null)
      return false;
    if (getClass() != obj.getClass())
      return false;
    Laptop other = (Laptop) obj;
    if (model == null) {
      if (other.model != null)
         return false;
    } else if (!model.equals(other.model))
      return false;
    if (price != other.price)
      return false;
    return true;
  }
}
----

There's a lot of boilerplate here, but IDEs can auto-generate these kinds of methods. In VS Code, for example, go to *Context Menu* > *Source Action* > *Generate hashcode() and equals()...*.
