= SSH Authentication with GitHub

You've already been added to the `hacksltd` GitHub organization – else you wouldn't be seeing this page. If you haven't already, you should generate an SSH key pair on your computer, and add the public key to GitHub as an SSH authentication key. You will need to have this in place before you can clone our repositories onto your computer.

== Prerequisites

If you don't already have an SSH key, see link:./key-generation.adoc[Key generation] first.

== Get your public key

Output the contents of your public key file:

[source]
----
less ~/.ssh/id_ed25519.pub
----

If you used RSA instead of ed25519:

[source]
----
less ~/.ssh/id_rsa.pub
----

== Add the public key to GitHub

Copy-and-paste the contents of the public key into your GitHub account settings. Go to **Settings** > **SSH and GPG keys** > **New SSH key**. Give the key a title, to identify it, and paste the contents of the public key. Set the key type to **Authentication Key**. In effect, you've added the public key to your `~/.ssh/authorized_keys` file on GitHub's servers.

== Test the connection

Test you can now authenticate with GitHub via SSH:

[source]
----
ssh git@github.com
----

You should get a result confirming you have successfully authenticated.

== Secure your private key

Keep your private key secure on your computer. If it leaks, you should revoke the corresponding public key from your GitHub account, and generate a new key pair.
