= Java: Strings

In Java, strings are a sequence of characters represented by the `String` class (not a primitive type). Strings can be created in several ways, but the most common is to use the double quote notation.

[source,java]
----
String name = "Kieran";
System.out.println(name); // "Kieran"

/* Equivalent to: */
String name2 = new String("Kieran");
System.out.println(name2); // "Kieran"

/* Equivalent to: */
char name3[] = {'K', 'i', 'e', 'r', 'a', 'n'};
System.out.println(name3); // "Kieran"
----

String instances have a number of methods for querying and manipulating the data, such as:

[source,java]
----
System.out.println(name.hashCode()); // -2047689704
System.out.println(name.length()); // 6
System.out.println(name.charAt(0)); // 'K'
----

In the following example, `n1` and `n2` exist on the stack, but they both point to the same `String` object that is stored in the heap memory. There's a thing called the string pool, which is a special area of heap memory for storing all the string values currently in use. If you create a new string with the same value as one that already exists in the pool, then the new variable (in the stack) will just point to the existing string value in the pool.

[source,java]
----
String n1 = "Kieran";
String n2 = "Kieran";
System.out.println(n1 == n2); // true (means the addresses are the same)
----

In Java, strings are immutable. This means, when you do operations like concatenation, the original string value is not changed in memory, and instead a new string is created in the string pool, and the variable is updated to point to this new string. Garbage collection will subsequently delete the old string value, if nothing else is pointing to it from the stack.

[source,java]
----
name = name + " Potts";
System.out.println(name); // "Kieran Potts"
----

If you want a genuinely mutable string, you can use `StringBuffer` or `StringBuilder`.

[source,java]
----
StringBuffer sb = new StringBuffer("Kieran");

/* Returns 16, the default capacity, which is the number of characters
that can be stored in the buffer without it having to resize itself. */
int bfSize = sb.capacity();
System.out.println(bfSize);

/* Length may be different from the capacity. */
System.out.println(sb.length()); // 6

/* Appending more characters to the string buffer. It's capacity will
automatically increase if necessary. */
System.out.println(sb); // "Kieran"
sb.append(" Potts");
System.out.println(sb); // "Kieran Potts"

/* There are lots of other methods for manipulating string buffers,
eg `deleteCharAt`, `insert`, `reverse`, etc. */
sb.reverse();

/* Returns the string buffer value as a standard String. */
String str = sb.toString();
System.out.println(str); // "sttoP nareiK"
----

`StringBuilder` works the same way as `StringBuffer`. The only difference between the two is that `StringBuffer` is thread-safe, whereas `StringBuilder` is not.
