= Java: Variables

A computer program is, essentially, responsible for processing input data and producing output data. During execution of a program, data will typically need to be temporarily stored in memory. This is the role of variables.

A variable is a container for a value or unit of data that is being operated on by the program.

When we create variables in Java, there are a few steps:

1. Specify the type of data that the variable wil hold. This determines what kind of data the variable can hold, eg. `int` for integers, `double` for decimals, `char` for characters, etc. This is known as *static typing*.

2. Give the variable a name. The name should be meaningful and follow Java's naming conventions, eg. `camelCase`.

3. Optionally, you can assign a value to the variable at the time of declaration. This is known as *initialization*.

[source,java]
----
int number = 10;
----

Alternatively, you can declare a variable without initializing it, and assign a value later:

[source,java]
----
int number;
----

When a variable is declared but not initialized, it will have a default value, which varies depending on its type. For example, variables of type `number` will have the value `0` by default. The default values are:

* `int`: 0
* `double`: 0.0
* `char`: '\u0000' (null character)
* `boolean`: false
* Objects, including `String`s: null
