= Java: Wrapper classes

Java is 99% object-oriented, but it is not 100% object oriented because it supports primitive data types. For example, int, float, etc. are primitive data types. They are not objects, as they do not have methods.

The advantage of primitive data types is improved performance. Low-level primitive values do not need to be stored in heap memory as objects.

For every primitive data type, there is a class in Java that represents it. These classes are called wrapper classes. They are used to convert primitive data types into objects and vice versa.

----
int -> Integer
char -> Character
double -> Double
etc.
----

The example below shows how we store a primitive value in an object. This concept is called *boxing*. This is the old syntax, and it is deprecated – it will emit an error on build:

[source,java]
----
int num = 7;
Integer i = new Integer(num);
----

The new syntax does the conversion automatically. This is called *autoboxing*.

[source,java]
----
int num = 7;
Integer i = num;

System.out.println(i); // 7
----

To get back the primitive value, we use *unboxing* methods like `intValue`.

[source,java]
----
int num = 7;
Integer i = num;

int num2 = i.intValue();
System.out.println(num2); // 7
----

You can also drop the use of the `intValue` method and use *auto-unboxing*.

[source,java]
----
int num = 7;
Integer i = num;

int num2 = i;
System.out.println(num2); // 7
----

You can also convert a string to an integer using `parseInt()`.

[source,java]
----
String str = "123";
int num = Integer.parseInt(str);

System.out.println(num); // 123
----
