= The Well-Architected Framework

AWS Well-Architected is a series of resources, tools that help you to design and implement high quality services on AWS, following best practices for cloud architecture.

AWS Well-Architected helps cloud architects to build secure, high-performing, resilient, and efficient infrastructure for their applications and workloads on AWS.

AWS Well-Architected consists of:

* The *Well-Architected Framework*, which itself is based on six *Well-Architected Pillars* of architectural best practices.

* *Well-Architected Tool*: Organizations input information about their existing workloads, via a series of questions, and the tool returns some guidance on where you could improve your architecture.

* *Well-Architected Lenses*: This is a series of guidance and best practices that are tailored to specific industry verticals, such as healthcare or data analytics, or specific technology areas. such as containers or serverless.

* *Well-Architected Guidance*: This is general guidance, not necessarily aligned to the Well-Architected Pillars, that is focused on specific use cases, technology areas, and implementation scenarios.

* *AWS Architecture Center*: This section of the AWS website is a large repository of lots of architectural patterns for different solutions.

* *Partners* who work with AWS and their customers to help them deliver solutions according to the Well-Architected best practices.

For more information, see: +
https://aws.amazon.com/architecture/well-architected/

== The Well-Architected Framework

The *Well-Architected Framework* helps you to understand the pros and cons of decisions you make when building systems on AWS.

It is based on six pillars — the *Well-Architected Pillars*:

1 - *Operational Excellence*: This pillar focuses on running and monitoring systems, and continually improving processes and procedures. Key topics include automating changes, responding to events, and defining standards to manage daily operations.

Best practices for operational excellence include:

* Performing operations as code (eg. using CloudFormation or another IaC solution, rather than manually building out infrastructure).

* Making frequent, small, reversible changes (to minimize the potential impact of deployments and make it easy to rollback if you need to.

* Refining operations procedures frequently.

* Anticipate failure (assume things will fail, know what you will do when they do fail, and build-in resilience to reduce the likelihood of failures in the first place).

* Learn from operational failures (use post-mortems to understand what went wrong and how to prevent it from happening again).

2 - *Security*: The security pillar focuses on protecting information and systems. Key topics include confidentiality and integrity of data, managing user permissions, and establishing controls to detect security events.

Best practices for security include:

* Implement a strong identity foundation, eg. enabling federation with an external identity provider.
* Enable traceability.
* Apply security at all layers; security is done in-depth.
* Automate security best practices.
* Protect data in transit and at rest.
* Keep people away from data.
* Prepare for security events.

3 - *Reliability*: The reliability pillar focuses on workloads performing their intended functions and how to recover quickly from failure to meet demands. Key topics include distributed system design, recovery planning, and adapting to changing requirements.

Best practices for reliability include:

* Automatically recover from failure.
* Test recovery procedures. Don't assume DR will work when it needs to — it probably won't.
* Scale horizontally to increase aggregate workload availability.
* Stop guessing capacity — this is a big benefit of AWS, we can accurately measure capacity and utilization, and adjust capacity as needed.
* Automate change procedures as much as possible.

4 - *Performance Efficiency*: This pillar focuses on structured and streamlined allocation of IT and computing resources. Key topics include selecting resource types and sizes optimized for workload requirements, monitoring performance, and maintaining efficiency as business needs evolve.

Best practices for performance efficiency include:

* Democratize advanced technologies (this is about using some of AWS's higher-level services to their best advantage).
* Go global in minutes (using the AWS global infrastructure to deploy your application around the world).
* Use serverless architectures (move away from managing your own servers wherever you can).
* Experiment more often — use the features and benefits of the cloud to experiment and test.
* Consider mechanical sympathy: understand how your systems work and how the components interact with each other.

5 - *Cost Optimization*: This pillar focuses on avoiding unnecessary costs. Key topics include controlling fund allocation, selecting resources of the right type and quantity, and scaling to meet business needs without overspending. In short, this is about delivering business value at the lowest cost.

Best practices for cost optimization include:

* Implement Cloud Financial Management.
* Adopt a consumption model.
* Measure overall efficiency.
* Stop spending money on undifferentiated heavy lifting (ie. the things you used to do outside of AWS, like buying servers and running your own data centers, etc.).
* Analyze and attribute expenditure.

6 - *Sustainability*: This pillar focuses on minimizing the environmental impacts of running cloud workloads. Key topics include a shared responsibility model for sustainability (ie. both AWS and its customers are responsible for this), understanding impact, and maximizing utilization to minimize required resources and reduce downtime impacts.

AWS is responsible for optimizing the sustainability _of_ the cloud — delivering efficient, shared infrastructure, water stewardship, and sourcing renewable power.

Customers are responsible for sustainability _in_ the cloud — optimizing workflows and resource utilization, and minimizing the total resources required to be deployed for your workloads.
