= AWS Organizations

AWS Organizations are used to manage multiple AWS accounts from a central location.

Within an *AWS Organization* you create a *Management Account*, which is at the root of the hierarchy we create in the AWS Organization.

We can then create additional accounts, or invite existing accounts, into the Organization. This can be done via the AWS Console or the AWS CLI using the *Organizations API*.

For example, you might create a *Production* account and a *Development* account, all under the same Organization. Those accounts are managed by the Management Account for the Organization. There must also be a *root* account, which is the account that was used to create the Organization.

It is a common pattern in large organizations to have multiple AWS accounts all managed under one AWS Organization. It allows the control of resources and permissions to be separated out by account.

The accounts are organized into *Organizational Units* (OUs), which is how you can group accounts together and form a hierarchy of accounts.

You can then attach policies, such as *Service Control Policies (SCPs)*, to the OUs or the root account. These will apply to all accounts within that OU or root account. The SCP will determine the permissions that are allowed within the organizational unit.

== Consolidated billing

Another feature of AWS Organizations is the ability for a Management Account to receive a *consolidated bill* for all accounts within its Organization. The bill will show the usage and costs of each account within the Organization – known as the *Linked Accounts*.

Consolidated billing includes a *Paying Account*, which is independent and cannot access the resources of other accounts. The paying account is used exclusively for billing purposes.
