= Poetry

Poetry is a dependency management and packaging tool for Python projects.

Production dependencies are added to the `pyproject.toml` file using the command:

[source]
----
$ poetry add <package-name>
----

Development dependencies are added using the command:

[source]
----
$ poetry add --group dev <package-name>
----

Linting, testing, and build tools should generally be added to a group called "dev".

You can install specific versions of packages, eg.:

[source]
----
$ poetry add --group dev ruff@^0.1.0
----

Alternatively you can manually edit Poetry's `pyproject.toml` file to add dependencies:

[source, toml]
----
[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.group.dev.dependencies]
ruff = "^0.1.0"
----

Then run the following command to install the dependencies:

[source]
----
$ poetry install
----

The CLIs of packages that are managed by Poetry can be accessed via the `poetry run` command, eg.:

[source]
----
poetry run ruff check .
poetry run ruff format .
----

You can check if a dependency is installed:

[source]
----
poetry show ruff
----

Poetry uses virtual environments to isolate project dependencies. You can check which virtual environment Poetry is using for the current project with the command:

[source]
----
poetry env info
----

If you want to do a clean `poetry install` of all your project's dependencies, you can remove the existing virtual environment with the following command:

[source]
----
poetry env remove <env-name>
----