= Providers

Providers are a logical abstraction of an upstream API that exposes certain resources, such as web services or databases. Providers are typically cloud service providers such as AWS, Azure, or GCP, or they may be services such as Kubernetes.

Providers are configured in Terraform files in "provider blocks", eg.:

[source]
----
provider "aws" {
  region = "eu-west-2"
  access_key = "AKIA..."
  secret_key = "yvDpm..."
}
----

Developers SHOULD NOT hard-code credentials in Terraform files. Instead, credentials SHOULD be set in profiles, which are configured in `~/.aws/credentials` (or the equivalent for other providers).

In the following example, the credentials are loaded from the "default" profile.

[source]
----
provider "aws" {
  profile = "default"
  region = "eu-west-2"
}
----

.~/.aws/credentials
[source]
----
[default]
aws_access_key_id = AKIA...
aws_secret_access_key = yvDpm...
----

To configure providers, follow the relevant documentation in the Terraform registry. The documentation for the AWS provider is here:

https://registry.terraform.io/providers/hashicorp/aws/latest/docs
