= Java: Console input

There are several APIs to read user input in Java.

The most basic API is `System.in.read()`, which captured the ASCII value of only the first inputted character.

[source,java]
----
import java.io.IOException;

System.out.println("Enter a number:");

try {
  int num = System.in.read();
  System.out.println("ASCII value of first character: " + num);
} catch (IOException e) {
  e.printStackTrace();
}
----

`BufferedReader` is more commonly used for reading lines of text input from the console. `BufferedReader` is a built-in class specifically designed for working with IO.

[source,java]
----
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.IOException;

System.out.println("Enter a number:");

try {
  InputStreamReader input = new InputStreamReader(System.in);
  BufferedReader reader = new BufferedReader(input);

  /* Convert string value of input to integer: */
  int num = Integer.parseInt(reader.readLine());
  System.out.println(num);

  reader.close();
} catch (IOException e) {
  e.printStackTrace();
}
----

`BufferReader` can also capture input from files and networks and other sources of input to a program. In the above example, `InputStreamReader` is used to read input from the console.

`BufferedReader` instances are a type of *resource*. Whenever you open a resource – like a file, network connection, or database – it is your responsibility to close it again, when you are done with it. This is best practice to free-up resources for optimization.

Finally, since Java v1.5, there is a newer API for reading input from the console. It is a utility class called `Scanner`. The `System.in` argument refers to input captured from the console rather than, say, a file or network connection.

[source,java]
----
import java.util.Scanner;

System.out.println("Enter a number:");

Scanner scanner = new Scanner(System.in);
int num = scanner.nextInt();
scanner.close();

System.out.println(num);
----
