= Terraform: Benefits

Terraform – and infrastructure-as-code (IaC) more generally – has many benefits over traditional manual infrastructure management approaches. Here are some of the key benefits of using Terraform.

* *High abstraction*: Terraform provides a declarative way of defining cloud infrastructure. This is done through a model revolving around the concepts of "providers" and "resources". This very high level of abstraction makes it possible to manage all kinds of infrastructure resources in a consistent way. You can use code to represent everything from virtual machines and containers to physical servers and network devices; from databases to load balancers; and from DNS records to third-party transactional email services.

* *Scalability*: You can use Terraform to manage everything from a single application to an entire data center.

* *Multi-cloud*: Terraform is cloud-agnostic and can be used to manage resources across multiple cloud providers, and even across your own on-premises infrastructure.

* *Stateful*: The state of your infrastructure is tracked by Terraform in a state file, which serves as a single source-of-truth for what your infrastructure looks like at any moment in time. Terraform itself uses this state file to determine what changes need to be made to your infrastructure, so that the infrastructure matches your desired configuration when you `apply` changes.

* *Version controlled*: Terraform's infrastructure configuration files are plain text files that can be put under version control, like any other text file. This allows you to track changes to your infrastructure over time, and to collaborate with others on your infrastructure configuration,using conventional development workflows. Infrastructure configuration may be maintained alongside application code – perhaps even in the same repository.

* *Declarative*: You declare what you want the end state of your infrastructure to be, and Terraform builds it. You don't need to write out a bunch of imperative commands to create, update, or delete resources. Terraform figures that out for you.

* *No manual click-ops*: You don't need to manually manage infrastructure via your cloud provider's web console or CLI. As well as being time-consuming, this manual approach to infrastructure management also has other overheads, such as the management of access permissions and the tracking of changes.

* *Reduced risk of human error*: Terraform separates the _planning_ of infrastructure from the _execution_ of infrastructure changes. An _execution plan_ determines which resources will be created, destroyed, or modified; tools like `terraform graph` can help to visualize the sequencing of changes. The execution plan can be inspected before the changes are applied, reducing risks from human error. With Terraform, we can declare what we want, test it, and _then_ apply the changes with confidence.

* *High levels of automation* are possible when infrastructure is defined as code. For example, infrastructure can be automatically provisioned and destroyed as part of a CI/CD process – plugged in to your existing development operations.

* *Cost savings* can be achieved, for example by tearing down non-production infrastructure at the end of each working day, so you're not paying for those resources outside of office hours. Commercial editions of Terraform also support automated cost estimation at the infrastructure planning stage.

* *Disaster recovery*: You can more quickly restore your infrastructure in the event of a disaster such as a data center outage. Because of the increased speed with which infrastructure can be recreated from scratch, you may choose to save further money by not maintaining "hot standby" environments.
