= Terraform: CLI and workflow

== Initializing

Whenever you create a new Terraform config, you need to run `terraform init` from the directory containing the config files.

This "initializes the back-end", which is to say it downloads and enabled the plugins (binary files) necessary to interact with your infrastructure provider.

----
$ terraform init

Initializing the backend...

Initializing provider plugins...
- Finding latest version of hashicorp/aws...
- Installing hashicorp/aws v4.53.0...
----

This generates a lock file called `.terraform.lock.hcl`. It is RECOMMENDED to commit this to source control, which guarantees that everyone will install the exact same dependencies when they run `terraform init` at the same commit point.

[IMPORTANT]
======
It is RECOMMENDED to always run `terraform init` before running any additional `terraform` commands, after pulling changes from source control.
======

== Planning

Run `terraform plan` to see what changes are required to update your infrastructure to match the desired state, as specified in your infrastructure-as-code.

Pass an `-out` option to output the plan to a file.

The changes will not be applied until you run `terraform apply`.

== Applying

Run `terraform apply` to apply the changes to your infrastructure.

[IMPORTANT]
======
It is RECOMMENDED to always run `terraform plan` before running `terraform apply`, to see what changes will be made. However, the `apply` operation will also ask you to confirm the changes before proceeding.
======

When applying, you can override any default values for variables – declared via `variables.tf` or `terraform.tfvars` – and used within the Terraform files, eg.:

----
$ terraform apply -var "instance_name="MyNewNameEC2"
----

If you have more than a few variables to set, then better to create a file called `terraform.tfvars` and set the variables there – that's the purpose of this file.

== Destroying

Running `terraform destroy` will destroy all of the infrastructure that is managed by the current Terraform config.

Do this whenever you have finished using resources, so you don't get charged for them.

Obviously, this is a destructive operation, so be careful when running it!

