= Terraform: Comparisons with other tools

Terraform overlaps with some of the capabilities of other tools:

* *Configuration management* tools such as https://www.chef.io/[Chef], https://www.puppet.com/[Puppet], and https://docs.ansible.com/ansible/latest/index.html[Ansible] are another category of *infrastructure automation tools*, but they are somewhat distinct from *infrastructure as code* tools such as Terraform. Configuration management tools automated the installation, configuration, and lifecycle management of software on machines that already exist. IaC and configuration management tools are often used together to manage both infrastructure resources and the bootstrapping of software on those resources. How that would work is you would configure Terraform with simple user scripts to install and activate a bootstrapping tool like https://cloud-init.io/[cloud-init], which would take care of the server's initial configuration, such as installing packages and setting up users and SSH keys. The bootstrapping tool would also install a configuration management agent such as Ansible, Chef, or Puppet, which would then take care of the ongoing configuration of the server, normally via a remote client.

* *Cloud-native IaC tools* like CloudFormation (for AWS) and Heat (for OpenStack) are direct competitors to Terraform but they are specific to a single cloud provider. What differentiates Terraform is that it is cloud-agnostic, meaning it can manage resources across multiple cloud providers and services. For example, Terraform can be used to orchestrate an AWS and OpenStack cluster simultaneously, while enabling third-party providers like Cloudflare and DNSimple to be integrated to provide CDN and DNS services. Thus Terraform can be used to manage an entire infrastructure, including its supporting services, instead of only a subset of it (which exists within a single provider).

* *Client libraries* such as Boto and Fog provide programmatic access to cloud providers' APIs. Some libraries focus on abstracting specific clouds, while others attempt to provide a common facade for multiple clouds, masking the semantic differences between them. These client libraries provide low-level access to cloud provider APIs, whereas infrastructure-as-code tools like Terraform provide a much higher-level of abstraction.

* *Container orchestration* tools like https://kubernetes.io/[Kubernetes] and https://www.docker.com/[Docker Swarm] are used to manage containers, which are a way of packaging and deploying applications. Terraform can be used to provision the underlying infrastructure on which container orchestration services run, but it is not a container orchestration tool itself. Thus, Terraform and Kubernetes can be used together: Terraform manages the lifecycle of the Kubernetes clusters, while Kubernetes manages the lifecycle of the containers running on those clusters.
