= Terraform: Functions

Terraform has a lot of https://developer.hashicorp.com/terraform/language/functions[built-in functions] that can be used to manipulate data, perform calculations, and transform values. These functions can called from within any expression.

You can experiment with the behavior of Terraform's built-in functions by using the Terraform console (run `terraform console`):

----
> max(5, 12, 9)
12
----

The available functions are summarized below.

== Numeric functions

* `abs()` — Returns the absolute value of the given number. If the number is zero or positive, the function returns the value as-is, but if it is negative, it is multiplied by -1 to make it positive before returning it.

* `ceil()` — Returns the closest whole number that is greater than or equal to the given value, which may be a fraction.

* `floor()` — Returns the closest whole number that is less than or equal to the given value, which may be a fraction.

* `log()` — Returns the logarithm of a given number in a given base.

* `max()` — Takes one or more numbers and returns the greatest number from the set.

* `min()` — Takes one or more numbers and returns the smallest number from the set.

* `parseint()` — Parses the given string as a representation of an integer in the specified base and returns the resulting number. The base must be between 2 and 62 inclusive.

* `pow()` — Calculates an exponent, by raising its first argument to the power of the second argument.

* `signum()` — Determines the sign of a number, returning a number between -1 and 1 to represent the sign.

== String functions

* `chomp()` — Removes newline characters at the end of a string.

* `endswith()` — Takes two values: a string to check and a suffix string. The function returns `true` if the first string ends with that exact suffix.

* `format()` — Produces a string by formatting a number of other values according to a specification string. It is similar to the printf function in C, and other similar functions in other programming languages.

* `formatlist()` — Produces a list of strings by formatting a number of other values according to a specification string.

* `indent()` — Adds a specified number of spaces to the beginning of each line in a multi-line string, except for the first line.

* `join()` — Produces a string by concatenating all of the elements of the specified list of strings with the specified separator.

* `lower()` — Converts all cased letters in the given string to lowercase.

* `regex()` — Applies a regular expression to a string and returns the matching substrings.

* `regexall()` — Applies a regular expression to a string and returns a list of all matches.

* `replace()` — Searches a given string for another given substring, and replaces each occurrence with a given replacement string.

* `split()` — Produces a list by dividing a given string at all occurrences of a given separator.

* `startswith()` — Takes two values: a string to check and a prefix string. The function returns `true` if the string begins with that exact prefix.

* `strcontains()` — Checks whether a substring is within another string.

* `strrev()` — Reverses the characters in a string. That the characters are treated as Unicode characters.

* `substr()` — Extracts a substring from a given string by offset and (maximum) length.

* `templatestring()` — Renders a string, defined elsewhere in the module, as a template using a set of variables. The primary use case for the `templatestring()` function is to render templates fetched as a single string from remote locations.

* `title()` — Converts the first letter of each word in the given string to uppercase.

* `trim()` — Removes the specified set of characters from the start and end of the given string.

* `trimprefix()` — Removes the specified prefix from the start of the given string, but only once. If the string does not begin with the prefix, the original string is returned unchanged.

* `trimsuffix()` — Removes the specified suffix from the end of the given string, but only once, even if the suffix appears multiple times. If the suffix does not appear at the very end of the string, the original string is returned unchanged.

* `trimspace()` — Removes any space characters from the start and end of the given string.

* `upper()` — Converts all cased letters in the given string to uppercase.

== Collection functions

* `alltrue()` — Returns `true` if all elements in a given collection are `true` or `"true"`. It also returns `true` if the collection is empty.

* `anytrue()` — Returns `true` if any element in a given collection is `true` or `"true"`. It also returns `false` if the collection is empty.

* `chunklist()` — Splits a single list into fixed-size chunks, returning a list of lists.

* `coalesce()` — Takes any number of arguments and returns the first one that isn't null or an empty string.

* `coalescelist()` — Takes any number of list arguments and returns the first one that isn't empty.

* `compact()` — Takes a list of strings and returns a new list with any null or empty string elements removed.

* `concat()` — Takes two or more lists and combines them into a single list.

* `contains()` — Determines whether the list, tuple, or set given in its first argument contains at least one element that is equal to the value in the second argument, using the same definition of equality as the `==` operator.

* `distinct()` — Takes a list and returns a new list with any duplicate elements removed.

* `element()` — Retrieves a single element from a list by its index.

* `flatten()` — Takes a list and replaces any elements that are lists with a flattened sequence of the list contents.

* `index()` — Finds the first element index for a given value in a list.

* `keys()` — Takes a map and returns a list containing the keys from that map.

* `length()` — Determines the length of a given list, map, or string.

* `list()` — *Deprecated* – replaced by `tolist()`.

* `lookup()` — Retrieves the value of a single element from a map, given its key. If the given key does not exist, the given default value is returned instead.

* `map()` — *Deprecated* – replaced by `tomap()`.

* `matchkeys()` — Constructs a new list by taking a subset of elements from one list whose indexes match the corresponding indexes of values in another list.

* `merge()` — Takes an arbitrary number of maps or objects, and returns a single map or object that contains a merged set of elements from all arguments.

* `one()` — Takes a list, set, or tuple value with either zero or one elements. If the collection is empty, one returns null. Otherwise, one returns the first element. If there are two or more elements then one will return an error.

* `range()` — Generates a list of numbers using a start value, a limit value, and a step value.

* `reverse()` — Takes a sequence and produces a new sequence of the same length with all of the same elements as the given sequence but in reverse order.

* `setintersection()` — Takes multiple sets and produces a single set containing only the elements that all of the given sets have in common.

* `setproduct()` — Finds all of the possible combinations of elements from all of the given sets by computing the _Cartesian product_.

* `setsubtract()` — Returns a new set containing the elements from the first set that are not present in the second set. In other words, it computes the _relative complement_ of the second set.

* `setunion()` — Takes multiple sets and produces a single set containing the elements from all of the given sets – In other words, it computes the union of the sets.

* `slice()` — Extracts some consecutive elements from within a list.

* `sort()` — Takes a list of strings and returns a new list with those strings sorted lexicographically.

* `sum()` — Takes a list or set of numbers and returns the sum of those numbers. Fails when given an empty list or set.

* `transpose()` — Takes a map of lists of strings and swaps the keys and values to produce a new map of lists of strings.

* `values()` — Takes a map and returns a list containing the values of the elements in that map.

* `zipmap()` — Constructs a map from a list of keys and a corresponding list of values.

== Encoding functions

* `base63decode()` — Takes a string containing a Base64 character sequence and returns the original string.

* `base64encode()` — Applies Base64 encoding to a string.

* `base64gzip()` — Compresses an HCL string using gzip and then encodes the string using Base64 encoding.

* `csvdecode()` — Decodes a string containing CSV-formatted data and produces a list of maps representing that data.

* `jsondecode()` — Interprets a given string as JSON, returning a representation of the result of decoding that string.

* `jsonencode()` — Encodes a given value to a string using JSON syntax.

* `textdecodebase64()` — Decodes a string that was previously Base64-encoded, and then interprets the result as characters in a specified character encoding.

* `textencodebase64()` — Encodes the unicode characters in a given string using a specified character encoding, returning the result base64 encoded.

* `urlencode()` — Applies URL encoding to a given string.

* `yamldecode()` — Parses a string as a subset of YAML, and produces a representation of its value.

* `yamlencode()` — Encodes a given value to a string using YAML 1.2 block syntax.

== Filesystem functions

* `abspath()` — Takes a string containing a filesystem path and converts it to an absolute path. If the inputted path is not absolute, it will be joined with the current working directory.

* `dirname()` — Takes a string containing a filesystem path and removes the last portion from it. If the path is empty then the result is ".", representing the current working directory.

* `pathexpand()` — Takes a filesystem path that might begin with a `~` segment, and if so it replaces that segment with the current user's home directory path. If the leading segment in the path is not `~` then the given path is returned unmodified.

* `basename()` — Takes a string containing a filesystem path and removes all except the last portion from it.

* `file()` — Reads the contents of a file at the given path and returns them as a string.

* `fileexists()` — Determines whether a file exists at a given path.

* `fileset()` — Enumerates a set of regular file names given a path and pattern.

* `filebase64()` — Reads the contents of a file at the given path and returns the contents as a base64-encoded string.

* `templatefile()` — Reads the file at the given path and renders its content as a template using a supplied set of template variables.

== Date and time functions

* `formatdate()` — Converts a timestamp into a different time format.

* `plantimestamp()` — Returns a UTC timestamp string in RFC 3339 format. This differs from `timestamp()` in that its return value will not change during the execution of a Terraform `plan` operation. Thus, this function is useful for generating a timestamp that represents the time of execution of a plan.

* `timeadd()` — Adds a duration to a timestamp, returning a new timestamp.

* `timecmp()` — Compares two timestamps and returns a number that represents the ordering of the timestamps: `0` if they are equal, `-1` if the first is earlier than the second, and `1` if the first is later than the second.

* `timestamp()` — Returns a UTC timestamp string in RFC 3339 format.

== Hash and cryptographic functions

* `base64sha256()` — Computes the SHA256 hash of a given string and encodes it with Base64. This is not equivalent to `base64encode(sha256("test"))` since `sha256()` returns hexadecimal representation.

* `base64sha512()` — Computes the SHA512 hash of a given string and encodes it with Base64. (This is not equivalent to `base64encode(sha512("test"))` since `sha512()` returns hexadecimal representation.

* `bcrypt()` — Computes a hash of the given string using the Blowfish cipher.

* `filebase64sha256()` — This function is a variant of `base64sha256()` that hashes the contents of a given file rather, than a literal string.

* `filebase64sha512()` — This function is a variant of `base64sha512()` that hashes the contents of a given file rather, than a literal string.

* `filemd5()` — This function is a variant of `md5()` that hashes the contents of a given file rather, than a literal string.

* `filesha1()` — This function is a variant of `sha1()` that hashes the contents of a given file rather, than a literal string.

* `filesha256()` — This function is a variant of `sha256()` that hashes the contents of a given file rather, than a literal string.

* `filesha512()` — This function is a variant of `sha512()` that hashes the contents of a given file, rather than a literal string.

* `md5()` — Computes the MD5 hash of a given string and encodes it with hexadecimal digits.

* `rsadecrypt()` — Decrypts an RSA-encrypted ciphertext, returning the corresponding cleartext.

* `sha1()` — Computes the SHA1 hash of a given string and encodes it with hexadecimal digits.

* `sha256()` — Computes the SHA256 hash of a given string and encodes it with hexadecimal digits.

* `sha512()` — Computes the SHA512 hash of a given string and encodes it with hexadecimal digits.

* `uuid()` — Generates UUID-format strings using random bytes.

* `uuidv5()` — Generates a name-based UUID, also known as a version 5 UUID.

== IP network functions

* `cidrhost()` — Calculates a full host IP address for a given host number within a given IP network address prefix.

* `cidrnetmask()` — Converts an IPv4 address prefix given in CIDR notation into a subnet mask address.

* `cidrsubnet()` — Calculates a subnet address within given IP network address prefix.

* `cidrsubnets()` — Calculates a sequence of consecutive IP address ranges within a particular CIDR prefix.

== Type conversion functions

* `can()` — Evaluates an expression and returns a boolean indicating whether the expression produces a result without any errors.

* `ephemeralasnull()` — Takes an ephemeral value and returns `null`. You might do this, for example, to output ephemeral values (which are values that are not stored in the state file) as `null` in the output, without actually destroying the underlying value (which other resources might depend on).

* `issensitive()` — Takes any value and returns `true` if Terraform treats it as sensitive.

* `nonsensitive()` — Take a value marked as sensitive and returns a copy that Terraform will not treat as sensitive.

* `sensitive()` — Takes any value and returns a copy that Terraform will treat like any input value marked as sensitive.

* `tobool()` — Converts its argument to a boolean type.

* `tolist()` — Converts its argument to a list type.

* `tomap()` — Converts its argument to a map type.

* `tonumber()` — Converts its argument to a number type.

* `toset()` — Converts its argument to a set type.

* `tostring()` — Converts its argument to a string type.

* `try()` — Evaluates all of its argument expressions in turn and returns the result of the first one that does not produce any errors.

* `type()` — Returns the type of a given value.

== Terraform-specific functions

* `provider::terraform::encode_tfvars()` — A rarely-needed function that takes an object value and produces a string containing a description of that object using the same syntax as the Terraform CLI would expect in a `.tfvars` file.

* `provider::terraform::decode_tfvars()` — A rarely-needed function that takes a string containing the content of a `.tfvars` file and returns an object describing the raw variable values it defines.

* `provider::terraform::encode_expr()` — A rarely-needed function that takes any value and produces a string containing Terraform language expression syntax approximating that value.
