= Terraform: Importing

If you have existing infrastructure – whether provisioned manually or using some other tool – that you want to start managing with Terraform, you can use the `terraform import` command to import it into a Terraform configuration.

You do need to start with some baseline Terraform configuration that defines the resource you want to import, but you don't need to specify any of the resource's attributes. Example:

[source,hcl]
----
resource "aws_instance" "node2" {
  # No attributes needed here, just the resource type and its name.
}
----

Then run `terraform init` to initialize a Terraform project.

----
$ terraform init
----

Then run `terraform import` to import the existing resource into the Terraform state:

----
$ terraform import aws_instance.node2 i-1234567890abcdef0
Import successful!
----

The arguments are:

* The resource type and name, in the format `<resource-type>.<resource-name>`.
* The instance ID, which is specific to the provider.

Unfortunately, the import command does not automatically generate the resource's configuration in the `.tf` files (it only imports the resource's attributes into the state files). You will need to manually add the resource block to your Terraform configuration files, if you want to be able to `apply` changes to it in the future.

[source,hcl]
----
resource "aws_instance" "node2" {
  ami                    = "ami-07dd19a7900a1f049"
  instance_type          = "t3.micro"
  ebs_optimized          = true
  tags = {
    "Name"  = "K8s Cluster Node-2"
  }
}
----

Use `terraform plan` to see what mandatory attributes are missing from the resource block, and then add them to the configuration. Terraform already has the state of the resource, so it will tell you what the values of the required attributes should be.

The Terraform documentation includes instructions to `terraform import` all types of resources of each providers – instances, VPCs, security groups, etc.

== Alternative import method

Since Terraform v1.5 you can import resources using `import` blocks in the `.tf` files. This is a more declarative way of importing resources, but it is still only semi-automatic like `terraform import`.

[source,hcl]
----
import {
  # Import a security group.
  from = "sg-12345678"
  to   = aws_security_group.web_sg
}
----

Then run:

----
$ terraform init
$ terraform plan -generate-config-out=generated.tf
----

The second command will generate a new file called `generated.tf` that contains the configuration for the imported resource.

.generated.tf
[source,hcl]
----
resource "aws_security_group" "web_sg" {
  # Attributes.
}
----

You can then run `terraform apply` to apply the changes to the state file. You can then delete the `import` block from the `.tf` file, and reorganize your Terraform configuration as needed.
