= Terraform: State

The `terraform.tfstate` file is generated by Terraform to keep track of the current state of the infrastructure that Terraform is managing. It maps real-world resources to configuration.

The file's contents are formatted as JSON for easy readability, though the file is not intended to be edited manually.

The file is committed to private source control, typically. Otherwise this file should be backed up securely.

The file should be treated as sensitive data, as it may contain secrets, such as credentials and IP addresses that are used to access your infrastructure. It is RECOMMENDED to encrypt the file at rest.

When you run `terraform apply`, Terraform uses this file to detect what changes need to be made to your infrastructure to reach the desired state as defined in your infrastructure-as-code files. Thus, Terraform can compute the difference between the current and desired configuration, and apply only the minimal changes necessary to reach the desired state.

Terraform also uses this file to record dependency relationships between resources, which helps it compute the correct sequencing of operations when creating or modifying resources. (Otherwise Terraform will try to `apply` changes in parallel.)

By maintaining this state file, Terraform can manage your infrastructure efficiently. For example, the `terraform apply` operation becomes idempotent, meaning that you can run it multiple times and Terraform will only change what's necessary to change since the last time it was run.

.Example terraform.tfstate
[source,json]
----
{
  "version": 4,
  "terraform_version": "1.9.8",
  "serial": 27,
  "lineage": "707b94a7-1e85-fc0e-572e-a82b165190b7",
  "outputs": {},
  "resources": [],
  "check_results": null
}
----
