= Terraform: Workspaces

Terraform Workspaces is a feature that allows you to manage multiple identical resources using the same configuration.

Workspaces is a CLI feature with five main commands:

* `terraform workspace new` – creates a new workspace
* `terraform workspace select` – switches to a different workspace
* `terraform workspace list` – lists all workspaces
* `terraform workspace show` – shows the current workspace
* `terraform workspace delete` – deletes a workspace

In Terraform, you always work in workspaces. By default, you start in the `default` workspace.

----
$ terraform workspace show
default
----

To create a new workspace, run:

----
$ terraform workspace new <workspace-name>
----

eg.

----
$ terraform workspace new staging
----

Terraform will create a new workspace with the name `staging`, and switch to it automatically.

----
$ terraform workspace list
  default
* staging

----

Imagine that your Terraform back-end is configured as follows:

[source,hcl]
----
terraform {
  backend "s3" {
    bucket = "terraform-remote-state-123456"
    key    = "prod/terraform.tfstate"
    region = "us-west-2"
  }
}
----

Now that you have switched to the `staging` workspace, Terraform will create a new state file in the same S3 bucket, but its key will be `env:/staging/prod/terraform.tfstate`. The `env:/<workspace-name>/` prefix is automatically added to the key to distinguish the state files for different workspaces.

If you ran `terraform apply` now, in the `staging` workspace, it would create from scratch all the resources defined in your Terraform configuration – effectively creating a duplicate of all the resources managed in the `default` workspace.

If you use workspaces, it is RECOMMENDED to include the workspace name in the resource names, so that in your cloud provider you can easily distinguish between resources that are managed by different Terraform workspaces.

[source,hcl]
----

resource "aws_instance" "web" {
  // ...
  tags = {
    Name  = "PROD WebServer - ${terraform.workspace}"
  }
}
----

By default, you cannot delete a workspace that would leave resources "dangling" in your cloud provider, unmanaged by Terraform. You SHOULD first destroy all the resources in a workspace before deleting the workspace itself.

----
$ terraform workspace select <workspace-name>
$ terraform destroy
----

You MUST be in a different workspace to delete another:

----
$ terraform workspace select default 
$ terraform workspace delete <workspace-name>
----

If you really want to delete a workspace without destroying its resources, you can use the `-force` flag:

----
$ terraform workspace delete <workspace-name> -force
----

[IMPORTANT]
======
Workspaces SHOULD be used only for testing infrastructure deployments, not for managing different environments (eg. production, staging, development). To manage different environments, you SHOULD use separate Terraform configurations, in different directories for each environment. Common configurations can be shared using Terraform modules.
======
