= Java: Threads

Modern operating systems support *multi-tasking*, which means that multiple processes (each running a discrete program) can run concurrently. In practice, multi-tasking is implemented by the operating system switching between processes so quickly that it appears as if they are running simultaneously. This is known as time-sharing or time-slicing.

NOTE: Multi-tasking is different from *multi-processing*, which means that multiple processes can run on multiple processors. Multi-core CPUs, which have multiple processing units on a single chip, enable multi-processing on a single device.

Each process can have multiple threads. A thread is the smallest unit of execution within a process. Threads withing a process share the same memory space and resources, but each thread has its own call stack and local variables.

Threads are a lightweight way to achieve parallelism within a process. Threads can be used by a single program to perform multiple tasks simultaneously, such as downloading files while displaying a progress bar, or processing data while updating a user interface.

Java supports *multi-threading*, which means that a Java program can have multiple threads running concurrently.

To design a class to execute in a separate thread, it's a simple matter of extending the `Thread` class.

[source,java]
----
class A extends Thread {
  public void run() {
      // …
  }
}
----

However, this is NOT the recommended way to create a thread in Java. The RECOMMENDED way is to implement the `Runnable` interface. This is because Java does not support multiple inheritance, and so if you extend the `Thread` class, you cannot extend any other class.

The built-in `Thread` class also implements the `Runnable` interface. So, when you extend the `Thread` class, you're actually implementing the `Runnable` interface, anyway.

[source,java]
----
class A implements Runnable {
  public void run() {
    for(int i=1;i<50;i++) {
        System.out.println("hi");

      /*
      The `sleep()` method is used to pause the execution of the current
      thread for a specified period of time. This gives the scheduler
      a chance to run other threads. It's included here only to
      demonstrate the interleaving of the two threads in the output.
      */

      try {
        Thread.sleep(10);
      } catch(InterruptedException e) {
        e.printStackTrace();
      }
    }
  }
}

class B implements Runnable {
  public void run() {
    for(int i=1;i<50;i++) {
      System.out.println("hello");

      try {
        Thread.sleep(10);
      } catch(InterruptedException e) {
        e.printStackTrace();
      }
    }
  }
}
----

To use a class that extends the `Thread` class, do this:

[source,java]
----
Thread a = new A();
Thread b = new B();
----

If the classes implement the `Runnable` interface, the code would be:

[source,java]
----
Runnable a = new A();
Runnable b = new B();
----

Threadable classes can also be implemented using anonymous classes


[source,java]
----
Runnable runnable = new Runnable() {
  public void run() {
    for(int i=1;i<50;i++) {
      System.out.println("hello");

      try {
        Thread.sleep(10);
      } catch(InterruptedException e) {
        e.printStackTrace();
      }
    }
  }
};
----

`Runnable` is also a functional interface, so you can alternatively use a lambda expression to implement it.

[source,java]
----
Runnable runnable = () -> {
  for(int i=1;i<50;i++) {
    System.out.println("hello");
    try {
      Thread.sleep(10);
    } catch(InterruptedException e) {
      e.printStackTrace();
    }
  }
};
----

You can signal to the operating system the priority order of threads. This is done by setting the priority of a thread using the `setPriority()` method. The priority of a thread is a suggestion to the operating system's scheduler about how the thread should be scheduled relative to other threads. However, it does not guarantee that threads with the highest priorities will always run ahead of other threads.

[source,java]
----
Thread ta = new Thread(a);
Thread tb = new Thread(b);

System.out.println(ta.getPriority()); // 5
System.out.println(tb.getPriority()); // 5

ta.setPriority(10);
tb.setPriority(Thread.MIN_PRIORITY); // or use built-in constants

System.out.println(ta.getPriority()); // 10
System.out.println(tb.getPriority()); // 1
----

To start a thread, we call the `start()` method. Internally, `start()` calls the `run()` method of the `Runnable` interface.

[source,java]
----
ta.start();
tb.start();
----

== Race conditions

Be wary of doing mutations on the same data in multiple threads. If two threads try to modify the same data at the same time, they can interfere with each other, leading to unpredictable results.

This is known as a *race condition*.

To prevent race conditions, do one of the following:

* Work only with immutable data.
* Make methods thread-safe.

A thread-safe method means that it can be called by only one thread a time. Thus, if Thread A is currently executing a method called `increment()`, then Thread B will wait until Thread A is done before it too executes `increment()`.

In Java, you can use the `synchronized` keyword to "synchronize" a method or block of code. Synchronization ensures that only one thread can access a shared resource at a time, thus making the method thread-safe and preventing race conditions.

Consider the following program:

[source,java]
----
class Counter {
  private int count = 0;

  public synchronized void increment() {
    count++;
  }

  public int getCount() {
    return count;
  }
}

public class TheadDemo {
  public static void main(String[] args) {

    Counter counter = new Counter();

    Thread t1 = new Thread(() -> {
      for (int i = 0; i < 1000; i++) {
        counter.increment();
      }
    });

    Thread t2 = new Thread(() -> {
      for (int i = 0; i < 1000; i++) {
        counter.increment();
      }
    });

    t1.start();
    t2.start();

    try {
      t1.join();
      t2.join();
    } catch (InterruptedException e) {
      e.printStackTrace();
    }

    // Expected output: 2000
    System.out.println(counter.getCount());

  }
}
----

This is thread-safe.

The `count++` operation is actually three operations rolled into one:

* Read the value.
* Add one.
* Write the new value back to the `count` variable.

Therefore, if two threads tried to increment the count at the same time, they could override each other's changes, resulting in the final count being less than expected (2000, in this case).

So, adding the `synchronization` keyword to the signature of the method that executes `count++` prevents two threads from running this method concurrently, ensuring that only one thread can increment the count at a time.

Another thing that we need to do is to wait for the two threads to finish their work and then have them rejoin the main thread before we print the final count. This is done using the `join()` method on both threads. If we did not do this, the threads would continue to run in parallel after the `System.out.println(counter.getCount())` statement is executed, meaning the final count would be any number up to 2000.

== Thread states

A thread can be in one of several states:

* *New*: The thread has been created but has not yet started.
* *Runnable*: The thread is ready to run.
* *Running*: The thread is currently executing.
* *Waiting* (aka. blocked): The thread is waiting indefinitely for another thread to perform a particular action.
* *Dead*: The thread has finished running.

The `start()` method transitions a thread from the *New* state to the *Runnable* state. The thread is now waiting for the OS's scheduler to start. When the scheduler starts the thread in the CPU, the JVM changes the thread's state to *Running*. This is when the `run()` method is executed.

If the `sleep()` method is called, the thread transitions to the *Waiting* state. The thread will remain in this state until the sleep time has elapsed, at which point it will transition back to the *Running* state. Alternatively, the `wait()` method can be called, which will also transition the thread to the *Waiting* state, and it exits this state and returns to the *Runnable* state when another thread calls `notify()` or `notifyAll()`.

The `run()` method contains the code that the thread will execute. When the `run()` method finishes its execution, the thread transitions to the *Dead* state.

Threads can also be stopped with `stop()`, but this API is deprecated because it can leave programs in inconsistent states.
