= AWS Well-Architected: Overview

AWS Well-Architected is a series of resources, tools that help you to design and implement high quality services on AWS, following best practices for cloud architecture.

AWS Well-Architected helps cloud architects to build secure, high-performing, resilient, and efficient infrastructure for their applications and workloads on AWS.

AWS Well-Architected consists of:

* The *Well-Architected Framework*, which itself is based on six *Well-Architected Pillars* of architectural best practices.

* *Well-Architected Tool*: Organizations input information about their existing workloads, via a series of questions, and the tool returns some guidance on where you could improve your architecture.

* *Well-Architected Lenses*: This is a series of guidance and best practices that are tailored to specific industry verticals, such as healthcare or data analytics, or specific technology areas. such as containers or serverless.

* *Well-Architected Guidance*: This is general guidance, not necessarily aligned to the Well-Architected Pillars, that is focused on specific use cases, technology areas, and implementation scenarios.

* *AWS Architecture Center*: This section of the AWS website is a large repository of lots of architectural patterns for different solutions.

* *Partners* who work with AWS and their customers to help them deliver solutions according to the Well-Architected best practices.

For more information, see: +
https://aws.amazon.com/architecture/well-architected/
