= AWS Elastic Compute Cloud (EC2)

EC2 is the *Elastic Compute Cloud* service from AWS. It provides resizable compute capacity in the cloud. It falls into the category of *Infrastructure-as-a-Service (IaaS)*. AWS manages the underlying infrastructure. Customers manage everything from the operating system upwards.

An EC2 instance is basically a *virtual machine*, aka. virtual server.

AWS primarily uses the AWS Nitro hypervisor system, which is a combination of dedicated hardware and a lightweight hypervisor. Nitro supports both Type 1 ("bare metal") and Type 2 ("hosted") hypervisors. Type 1 hypervisors interact directly with the hardware, while Type 2 hypervisors run on top of a host operating system.

To determine which hardware resources are allocated to an EC2 instance, you choose an *instance type*. Each instance type has a specific combination of CPU, memory, storage, and networking capacity.

EC2 instance types are grouped into families based on their target use cases. For example, the `t3` family is designed for general-purpose workloads, while the `c5` family is optimized for compute-intensive workloads.

EC2 instances typically run Linux or Windows. There is also a version that runs macOS — but this is basically dedicated hardware and is therefore relatively expensive.

== EC2 instance types

|===
|Family |Type |vCPUs |Memory (GiB)

|General purpose
|t2.micro
|1
|1

|Compute-optimized
|c5n.large
|2
|5.25

|Memory-optimized
|r5ad.large
|2
|16

|Storage-optimized
|d2.xlarge
|4
|30.5

|CPU instances
|g2.2xlarge
|8
|15
|===

Instance types define the hardware, and therefore the cost.

When creating an EC2 instance, we also need to select which *Amazon Machine Image (AMI)* to use, eg. Linux or Windows. The AMI defines the configuration of the instance — the OS and other software such as databases that are installed by default. The AMI also defines the virtual drives ("volumes") associated with the instance.

An *EBS snapshot* is a point-in-time image of a running EC2 instance. EBS snapshots can be used for backup purposes, and also to create customized AMIs from which we can launch more instances with our own customizations.

== EC2 User Data

*EC2 User Data* can be added via the AWS Management Console. User Data is code that will be run when an EC2 instance is booted up the first time. User Data is a handy way to install some additional software or configuration that is not included in the image. The following example is used to install and enable a web server.

[source,bash]
----
#!/bin/bash

yum update -y
yum install -y httpd
systemctl start httpd
systemctl enable httpd
----

User Data is limited to 16KB in size, so its only good for simple scripts. For Windows instances, you can run Batch and Powershell scripts as well as Bash ones.

== EC2 Metadata

EC2 metadata is data about an EC2 instance. You can retrieve this metadata via a request to the following URL on the EC2 instance itself (`curl https://...`). The IP address used for this purpose is always the same.

----
http://169.254.169.254/latest/meta-data
----

The above example will return a list of metadata that you can request. You can then make further calls to retrieve specific metadata. For example, to return the instance's private IP address:

----
http://169.254.169.254/latest/meta-data/local-ipv4
----

== Access keys and user roles

Access keys and user roles are two ways that we can give EC2 instances — and, by extension, the applications running inside of them — permission to programmatically access other AWS resources and services.

*Access keys* are associated with IAM users and they grant all the permissions (via IAM *policies*) that the user has. Access keys are stored in plain text within a running EC2 instance. Access keys are long-term credentials, so they are convenient, but they are also less secure than user roles.

User *roles* are a more secure solution. No credentials are stored within a running EC2 instance, and the permissions are granted only temporarily. Like any other principal, an EC2 instance may "assume" a role for a short time, to gain temporary access to AWS resources and services, such as an S3 bucket.

We use the *Security Token Service (STS)* to get temporary access keys with the permissions associated with the requested role.
